name: admin_hub_app
description: Sunstone Educator app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+16

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  package_info_plus: ^3.0.3
  get: ^4.6.5
  beacon_broadcast: ^0.3.1
  permission_handler:
  flutter_svg: ^1.1.6
  firebase_core: ^2.4.0
  firebase_messaging: ^14.6.7
  firebase_auth: ^4.2.2
  google_sign_in: ^5.4.2
  lottie: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  image_picker: ^0.8.6
  device_info_plus:
  cached_network_image: ^3.2.3
  flutter_flavor: ^3.0.3
  dotted_border: ^2.0.0+3
  moengage_flutter: ^6.0.0
  firebase_remote_config: 4.2.5
  flutter_inappwebview: 5.8.0
  youtube_player_iframe: 3.1.0
  file_picker: 5.2.5
  fluttertoast: 8.0.9
  syncfusion_flutter_pdfviewer: 21.2.3
  open_filex: 4.3.2
  background_downloader: 5.6.0
  scrollable_positioned_list: 0.3.5
  table_calendar: 3.0.8
  flutter_linkify: 5.0.2
  sqflite: 2.3.0
  connectivity_plus: 5.0.1
  flutter_background_service: 5.0.2
  flutter_local_notifications: 16.1.0
  form_field_validator: ^1.1.0

  better_player:
    git:
      url: https://github.com/dev-sunstone/betterplayer
      ref: Issue1057

  ss_network:
    git:
      url: git@github.com:dev-sunstone/ss_network.git
      ref: "85b9f64"

  sunstone_ui_kit:
    git:
      url: git@github.com:dev-sunstone/ss-mobile-uiframework.git
      ref: "4b827df"

  ss_deeplink:
    git:
      url: git@github.com:dev-sunstone/ss_deeplink.git
      ref: "ae58458"

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dependency_overrides:
  http: 1.0.0
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  dart_code_metrics: ^5.7.6

flutter_flavor:
  dimensions:
    android: "flutter-flavor"
    ios: "flutter-flavor"

  flavors:
    dev:
      android:
        name: "Dev Sunstone Educator"
        applicationId: "com.sunstone.admin"

      ios:
        name: "Dev S Educator"
        bundleId: "com.sunstone.admin"

    staging:
      android:
        name: "Staging Sunstone Educator"
        applicationId: "com.sunstone.admin"

      ios:
        name: "Staging S Educator"
        bundleId: "com.sunstone.admin"

    prod:
      app:
        name: "Sunstone Educator"
        id: "com.sunstone.admin"

      android:
        name: "Sunstone Educator"
        applicationId: "com.sunstone.admin"

      ios:
        name: "S Educator"
        bundleId: "com.sunstone.admin"

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/svg/auth/
    - assets/lottie/
    - assets/icon/
    - assets/images/